// <auto-generated />
using CakeShop1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CakeShop1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210213153903_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CakeShop1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Классические торты"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Чизкейки"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Бисквитные торты"
                        });
                });

            modelBuilder.Entity("CakeShop1.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Классический Пражский торт, вкус которого знаком нам с детства. Бисквитные коржи пропитаны маслянистым кремом и покрытые шоколадной помадкой.",
                            ImageThumbnailUrl = "~\\Images\\praga.jpg",
                            ImageUrl = "~\\Images\\praga.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Пражский",
                            Price = 320m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Тонкая бисквитная основа, бисквитные палочки, пропитанные кофейным ликером, залитые кофейным кремом на основе сливок и белого шоколада с добавлением ликера. Изысканный торт.",
                            ImageThumbnailUrl = "~\\Images\\tiramisu2.jpg",
                            ImageUrl = "~\\Images\\tiramisu2.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Тирамису",
                            Price = 250m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Медовые коржи прослоены заварным кремом на основе сгущенного молока.",
                            ImageThumbnailUrl = "~\\Images\\medovik1.jpg",
                            ImageUrl = "~\\Images\\medovik1.jpg",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Медовик",
                            Price = 180m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Чизкейк три шоколада - изумительный десерт, который с лихвой оправдывает все Ваши ожидания. ",
                            ImageThumbnailUrl = "~\\Images\\3сhoсo.png",
                            ImageUrl = "~\\Images\\3сhoсo.png",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Три шоколада",
                            Price = 200m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Какая здесь вкусная и хрустящая карамельно-фисташковая основа! Просто объедение!  ",
                            ImageThumbnailUrl = "~\\Images\\fistashkoviy.png",
                            ImageUrl = "~\\Images\\fistashkoviy.png",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Фисташковый чизкейк ",
                            Price = 180m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Классический чизкейк, который представляет собой нежное сочетание сливочного крем-сыра и основы из песочного печенья.",
                            ImageThumbnailUrl = "~\\Images\\newYork.png",
                            ImageUrl = "~\\Images\\newYork.png",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Чизкейк Нью-Йорк ",
                            Price = 480m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Манговое блаженство, в нежном бисквитном торте, покрытым глазурью.",
                            ImageThumbnailUrl = "~\\Images\\mango.png",
                            ImageUrl = "~\\Images\\mango.png",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Манго",
                            Price = 510m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Шоколадный бисквит, пропитанный вишнево-ликерным сиропом, обеспечивает торту насыщенный вкус, а шоколадный крем с добавлением вишни, настоянной на ликере и роме, делает торт нежным и пикантным. ",
                            ImageThumbnailUrl = "~\\Images\\pyanayaVishniya.png",
                            ImageUrl = "~\\Images\\pyanayaVishniya.png",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Пьяная Вишня",
                            Price = 580m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3,
                            Description = "Шоколадный бисквит, клубнично-сливочный крем, кусочки свежей клубники.",
                            ImageThumbnailUrl = "~\\Images\\klubnichniy.png",
                            ImageUrl = "~\\Images\\pklubnichniy.png",
                            IsInStock = true,
                            IsOnSale = false,
                            Name = "Клубничный бисквит",
                            Price = 360m
                        });
                });

            modelBuilder.Entity("CakeShop1.Models.Product", b =>
                {
                    b.HasOne("CakeShop1.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
